version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    
    environment:
        POSTGRES_DB: pomodoro
        POSTGRES_USER: password
        POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
